"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const selectors_1 = require("../../util/selectors");
const resolvePath_1 = require("./util/resolvePath");
const reselect_1 = require("reselect");
const paths = (state) => state.settings.mods.paths;
exports.basePath = reselect_1.createSelector(paths, selectors_1.activeGameId, (inPaths, inGameMode) => resolvePath_1.default('base', inPaths, inGameMode));
exports.downloadPath = reselect_1.createSelector(paths, selectors_1.activeGameId, (inPaths, inGameMode) => resolvePath_1.default('download', inPaths, inGameMode));
exports.installPath = reselect_1.createSelector(paths, selectors_1.activeGameId, (inPaths, inGameMode) => resolvePath_1.default('install', inPaths, inGameMode));
exports.currentActivator = (state) => state.settings.mods.activator[selectors_1.activeGameId(state)];
