export declare const NEXUS_DOMAIN: string;
export declare const NEXUS_API_SUBDOMAIN: string;
export declare const NEXUS_FLAMEWORK_SUBDOMAIN: string;
export declare const NEXUS_NEXT_SUBDOMAIN: string;
export declare const NEXUS_USERS_SUBDOMAIN: string;
export declare const NEXUS_BASE_URL: string;
export declare const NEXUS_NEXT_URL: string;
export declare const NEXUS_PROTOCOL = "https:";
export declare const PREMIUM_PATH: string[];
export declare const FALLBACK_AVATAR = "assets/images/noavatar.png";
export declare const REVALIDATION_FREQUENCY: number;
export declare const OAUTH_URL: string;
export declare const USERINFO_ENDPOINT: string;
export declare const OAUTH_REDIRECT_BASE = "http://127.0.0.1";
export declare const getOAuthRedirectUrl: (port: number) => string;
export declare const OAUTH_REDIRECT_URL = "http://127.0.0.1:PORT";
export declare const OAUTH_CLIENT_ID = "vortex_loopback";
export declare const NEXUS_PUBLIC_KEY: string;
