name: Update Knowledgebase

on:
  issues:
    types: [edited, labeled, unlabeled]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run kb
    - run: git add docs/_posts/*
    - run: git commit -m "updated knowledge base"
    - run: git push
