name: Update Knowledgebase

on:
  issues:
    types: [edited, labeled, unlabeled]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run kb
    - name: Commit changes
      uses: EndBug/add-and-commit@v5
      with:
        author_name: TanninOne
        author_email: seppleviathan@gmx.de
        message: "updated knowledge base"
        add: "docs/_posts/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: git push
